shooting-stars-enabled: true
falling-stars-enabled: true
begin-spawning-stars-time: 13000
end-spawning-stars-time: 23000
shooting-stars-per-minute: 4
shooting-stars-min-height: 120
shooting-stars-max-height: 170
falling-stars-per-minute: 0.75
falling-stars-radius: 25
falling-stars-sound-enabled: true
falling-stars-volume: 6
falling-stars-spark-time: 20
falling-stars-experience: 200
falling-stars-loot:
 emerald: 30
 golden_carrot: 30
 gold_ingot: 25
 crying_obsidian: 10
 netherite_scrap: 5
new-moon-meteor-shower: true
shooting-stars-per-minute-during-meteor-showers: 15
falling-stars-per-minute-during-meteor-showers: 0.3
shooting-stars-summon-text: "<gradient:blue:aqua>Make a wish!"
falling-stars-summon-text: "<gradient:blue:aqua>Make a wish & grab the loot!"
debug: true
